#!/bin/bash
if [[ "$1" == "true" ]]; then
  sudo echo 'Acquire::http::Proxy "http://internet.ford.com:83/";' > /etc/apt/apt.conf.d/proxy.conf
  echo 'Acquire::https::Proxy "http://internet.ford.com:83/";' >> /etc/apt/apt.conf.d/proxy.conf
else
  rm -rf /etc/apt/apt.conf.d/proxy.conf
fi
