#!/bin/bash

#
# The purpose of this script is to have easy access to the 17a (oadBasicFTData + loadBasicInternalUserFTData) from the e2t scripts
#

cd /Users/gjdittri/elis/apps/Database; gradle baseline update -Ptoggle=ALL_ON; cd /Users/gjdittri/elis/apps/Shared/DataLoader; gradle clean build loadBasicFTData loadBasicInternalUserFTData
