#!/bin/bash

cd /Users/gjdittri/elis/apps/Database; gradle baseline update -Ptoggle=ALL_ON; cd /Users/gjdittri/elis/apps/Shared/DataLoader; gradle clean build loadBasicFTData loadBasicInternalUserFTData
