#!/bin/bash

secretValue="$(az keyvault secret show --name $1 --vault-name $2 | jq .value | tr -d '"')"

az keyvault secret set --name $1 --vault-name $3 --value $secretValue --expires "$(date -v+1y +%Y-%m-%dT%H:%M:%S'Z')"
