#!/bin/bash

#
# The purpose of this script is to run all the tasks needed after pulling master/switching branches
#

screen -dmSL gulp ./gulp&
screen -dmSL interface ./interface&
screen -dmsL 17a ./buildEverything

tail -f ~/scripts/screenlog.0
