#!/bin/bash

#
# WIP do not use!!!!
#

    deployFile=$HOME/scripts/deployTomcat
    if [ -x "$deployFile" ] ; then
        cd "$ELIS_HOME"; bash $deployFile deployAll
    else
        chmod +x $deployFile
        cd "$ELIS_HOME"; bash $deployFile deployAll
    fi

