#!/bin/bash


#
# The purpose of this branch is to automate creating a CI branch and feature branch when working on monolith tickets
#
# PARAM 1: Ticket Number (i.e. 62142 will create CI-Neuron_62142 and Neuron_62142)
#

TICKET_NUMBER="CI-Neuron_$1"

echo $TICKET_NUMBER

git checkout Staging; git pull origin Staging;

git checkout -b $TICKET_NUMBER -t origin/Staging

~/scripts/pull

~/scripts/push

MY_CURRENT_BRANCH=`git branch | grep \* | cut -d ' ' -f2`
MY_CURRENT_BRANCH=`echo $MY_CURRENT_BRANCH | cut -d '-' -f2`

git checkout -b $MY_CURRENT_BRANCH -t $TICKET_NUMBER

echo `echo $MY_CURRENT_BRANCH | cut -d '-' -f2`
