#!/bin/bash

TICKET_NUMBER="CI-Neuron_$1"

echo $TICKET_NUMBER

git checkout Staging; git pull origin Staging;

git checkout -b $TICKET_NUMBER -t origin/Staging

MY_CURRENT_BRANCH=`git branch | grep \* | cut -d ' ' -f2`

git checkout -b `echo $MY_CURRENT_BRANCH | cut -d '-' -f2` -t $TICKET_NUMBER

echo `echo $MY_CURRENT_BRANCH | cut -d '-' -f2`
